import numpy as np
from ScrapBooker import ScrapBooker
from ImageProcessor import ImageProcessor

spb = ScrapBooker()
arr1 = np.arange(0, 25).reshape(5, 5)
print("Test 1: CROP (3, 1), (1, 0)")
print(">> Before:")
print(arr1)
print(">> After:")
print(spb.crop(arr1, (3, 1), (1, 0)))
print("\nTest 2: THIN 3, 1")
arr2 = np.array("A B C D E F G H I J K".split() * 6).reshape(-1, 11)
print(">> Before:")
print(arr2)
print(">> After:")
print(spb.thin(arr2, 3, 1))
print("\nTest 3: JUXTAPOSE 3, 1")
arr3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(">> Before:")
print(arr3)
print(">> After:")
print(spb.juxtapose(arr3, 3, 1))
print("\nTest 4: MOSAIC 12, 12")
arr4 = np.array([['A', 'B'], ['C', 'D']])
print(">> Before:")
print(arr4)
print(">> After:")
print(spb.mosaic(arr4, (3, 3)))
print("\nTest 5: FAIL TESTS FOR EACH")
print(spb.crop(arr1, 2, 2))
print(spb.thin(arr2, 2, 2))
print(spb.juxtapose(arr3, 2, 2))
print(spb.mosaic(arr4, 2))
imp = ImageProcessor()
image = imp.load("../ex01/42AI.png")
imp.display(spb.crop(image, (110, 110), (50, 50)))
imp.display(spb.thin(image, 2, 0))
imp.display(spb.juxtapose(image, 12, 1))
imp.display(spb.mosaic(image, (12, 11)))
