from matrix import Matrix
from vector import Vector
from numpy import matlib

m1 = Matrix((1, 4))
# print("TEST 1 : v1 = Vector([[0.0], [1.0], [2.0], [3.0]])")
# v1 = Vector([[0.0], [1.0], [2.0], [3.0]])
# print(str(v1))
# print(v1.shape)
# print("TEST 2 : v1 / 2.0")
# print(str(v1 / 2.0))
# print("TEST 3 : 3.0 / v1")
# try:
#     print(str(3.0 / v1))
# except ValueError as e:
#     print("ValueError :", e)
# print("TEST 4 : v2 = Vector([0.0, 1.0, 2.0, 3.0])")
# v2 = Vector([0.0, 1.0, 2.0, 3.0])
# print(str(v2))
# print(v2.shape)
# print("TEST 5 : v2 * 4")
# print(str(v2 * 4))
# print("TEST 6 : Vector(6)")
# print(Vector(6).values)
# print(Vector(6).shape)
# print("TEST 7 : Vector((3, 6))")
# print(Vector((3, 6)).values)
# print(Vector((3, 6)).shape)
# print("TEST 8 : v1 + v2")
# try:
#     print(v1 + v2)
# except ValueError as e:
#     print("ValueError :", e)
# print("TEST 9 : v1 + v1 * 2")
# print(str(v1 + v1 * 2))
# print("TEST 10 : v1.T()")
# print(" => BEFORE")
# print(str(v1))
# print(v1.shape)
# print(" => AFTER")
# print(str(v1.T()))
# print(v1.T().shape)
# print("TEST 11 : v2.T()")
# print(" => BEFORE")
# print(str(v2))
# print(v2.shape)
# print(" => AFTER")
# print(str(v2.T()))
# print(v2.T().shape)
# print("TEST 12 : v1.dot(v1)")
# print(str(v1.dot(v1)))
# print("TEST 13 : v2.dot(v2)")
# print(str(v2.dot(v2)))
print(matlib.zeros((3, 2, 3)))