from NumPyCreator import NumPyCreator


npc = NumPyCreator()
print("TEST 1: from_list([[1, 2, 3], [6, 3, 4]])")
npobject = npc.from_list([[1, 2, 3], [6, 3, 4]])
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 2: from_list([[1, 2, 3], [6, 4]])")
npobject = npc.from_list([[1, 2, 3], [6, 4]])
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 3: from_list([[1, 2, 3], ['a', 'b', 'c'], [6, 4, 7]])")
npobject = npc.from_list([[1, 2, 3], ['a', 'b', 'c'], [6, 4, 7]])
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 4: from_list(((1, 2), (3, 4)))")
npobject = npc.from_list(((1, 2), (3, 4)))
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 5: from_tuple((\"a\",\"b\",\"c\"))")
npobject = npc.from_tuple(("a", "b", "c"))
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 6: from_tuple(([\"a\"], [\"b\"], [\"c\", \"d\"]))")
npobject = npc.from_tuple((["a"], ["b"], ["c", "d"]))
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 7: from_tuple([[1, 2, 3], [6, 3, 4]])")
npobject = npc.from_tuple([[1, 2, 3], [6, 3, 4]])
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 8: from_iterable(range(5))")
npobject = npc.from_iterable(range(5))
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 9: from_shape((3, 5))")
shape = (3, 5)
npobject = npc.from_shape(shape)
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 10: random((3, 5))")
npobject = npc.random(shape)
print(npobject, "\n Type :", type(npobject), end='\n\n')
print("TEST 11: identity(4)")
npobject = npc.identity(4)
print(npobject, "\n Type :", type(npobject))
